### ISSUE TITLE
Spread word on Crypto Salon, where do events go?

### ISSUE THREAD

**Issue by bmann** [Finhaven/blockchainYVR#4]
Thanks @please-wait for putting this up -- https://teamup.com/event/show/id/4bFAxhe92UHekXNbosvq5GYZ8SCRpF -- as a test.

I think it probably needs a longer description. How about:

---
The [Linux Foundation Open Source Summit is in Vancouver](https://events.linuxfoundation.org/events/open-source-summit-north-america-2018/) on August 29th to August 31st. Lots of interesting people will be around from out of town.

Drop by the DCTRL space on August 30th for an evening #cryptosalon. There will be some beverages for sale from the vending machine, and Vancouver locals from the open source, decentralization, and crypto communities. Open to all, a good excuse for conference attendees to meet some locals.

Let us know you're coming by registering here, and we'll send you an email reminder.

---

Also where do we put events? Should we do similar to how I built https://ethereumevents.global with the site?

I think I'll make an attempt at this. A place where we can make simple event landing pages, and then register through TeamUp. And still highlight the group calendar.

**Comment by please-wait** [comment]
Lovely, just updated it. @bmann for https://ethereumevents.global/ how people are notified that you posted a new event? Email newsletter? I anticipate very few use RSS.

**Comment by bmann** [comment]
People can subscribe / get notifications from the forum. I think that’s our main interactive channel where people can set their own preferences for notification. I can make a Meetup / Events sub-category — but let’s just use one forum category for now. 

We could run a mailing list. But it’s one more thing to run!

I don’t have a plan for EEG other than Twitter. It’s more of a resource like the TeamUp calendar so people can go to one place and see what’s going on. I might experiment with an email newsletter with event updates. We’ll see. 

Brainstorming:
- register by teamup
- register by GitHub issue
- Picatic
- Google Form
- no registration 

I think the problem we are trying to solve is — how many people are coming? remind people to come / communicate ahead of time. Get people to take an action (register) as part of commitment. 

Places to put event info:
- Jekyll - create a post per event
- GitHub wiki
- forum (we should probably announce events here in any case)

**Comment by please-wait** [comment]
Spot on. 

Idea: Github webhooks, or [Marketplace Apps](https://github.com/marketplace). Those are triggered every time the repo changes, i.e. when we post something new. What if that trigger sent everyone an email?

**Comment by please-wait** [comment]
@bmann did you get any reminders from teamup (reminders@teamup.com) for the Crypto Salon event?
